version: '3'

volumes:
  foodgram_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_data_production:/var/lib/postgresql/data
  backend:
    image: maximsupreme/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: maximsupreme/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
  gateway:
    image: maximsupreme/foodgram_gateway
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend