version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    image: maximsupreme/foodgram_backend
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    env_file: .env
    restart: always


  frontend:
    image: maximsupreme/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend


  nginx:
    image: maximsupreme/foodgram_nginx
    ports:
      - "9090:80"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
