version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foodgram_network


  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    env_file: .env
    networks:
      - foodgram_network


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend
    networks:
      - foodgram_network


  nginx:
    build: ../nginx/
    ports:
      - "9090:80"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network
