# version: '3'

# volumes:
#   db_data:
#   static:
#   media:

# services:
#   db:
#     image: postgres:13.10
#     env_file: .env
#     volumes:
#       - db_data:/var/lib/postgresql/data
#   backend:
#     container_name: backend
#     image: maximsupreme/foodgram_backend
#     env_file: .env
#     volumes:
#       - static:/backend_static
#       - media:/app/media
#     depends_on:
#       - db
#   frontend:
#     container_name: foodgram-front
#     build: maximsupreme/foodgram_frontend
#     command: cp -r /app/build/. /frontend_static/
#     volumes:
#       - ../frontend/:/app/result_build/
#   gateway:
#     container_name: foodgram-proxy
#     image: nginx:1.25.4-alpine
#     ports:
#       - 9090:80
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/
#     depends_on:
#       - backend
#       - frontend
version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
