# Generated by Django 5.1.7 on 2025-04-08 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='recipes_in_shopping_cart', through='api.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок пользователей.'),
        ),
    ]
