MAX_STRING_CHAR = 254
MAX_STR_AND_SLUG_CHAR = 64
MAX_LENGTH_USER_BIO_INFO = 150
MAX_ROLE_LENGTH = 60
MIN_PASSWORD_LENGTH = 8

ROLE_USER = 'user'
ROLE_ADMIN = 'admin'

ROLES = (
    ('ROLE_USER', 'User'),
    ('ROLE_ADMIN', 'Admin'),
)
