MAX_STRING_CHAR = 254
MAX_SLUG_CHAR = 50
MAX_LENGTH_USER_BIO_INFO = 150
MAX_ROLE_LENGTH = 60
MAX_STR_LENGTH = 15

ROLE_USER = 'user'
ROLE_ADMIN = 'admin'

ROLES = (
    ('ROLE_USER', 'User'),
    ('ROLE_ADMIN', 'Admin'),
)
